### ISSUE TITLE
Is version 0.29.2 published?

### ISSUE THREAD

**Issue by manolakis** [commonmark/commonmark.js#190]
I saw that master contains version 0.29.2 with ESM support, but I don't see it published in npm. Is it going to be released soon?

Thanks!

**Comment by GrahamCampbell** [comment]
Friendly ping @jgm. :)

**Comment by jgm** [comment]
It's not published yet, I'm sorry.  I could use some help from someone who knows something about modern JavaScript, actually.  When I try `make dist` I'm getting
```
[!] Error: Cannot find module '/Users/jgm/src/commonmark.js/node_modules/@rollup/plugin-node-resolve/dist/index.js'. Please verify that the package.json has a valid "main" entry
Error: Cannot find module '/Users/jgm/src/commonmark.js/node_modules/@rollup/plugin-node-resolve/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:337:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:702:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1052:27)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/jgm/src/commonmark.js/rollup.config.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/rollup/dist/shared/loadConfigFile.js:508:20)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
```
Any suggestions?

**Comment by colinodell** [comment]
I'm unfortunately unable to replicate that issue otherwise I'd help, but perhaps the commit referenced above from @justinribeiro will fix things?

**Comment by justinribeiro** [comment]
The only reason I didn't PR the above commit was because I too couldn't replicate the publish issue. The "fix" in that commit is at best semantic but _may_ solve it @jgm for your setup (but if said tiny rev doesn't change things, I'm happy to explore further with you).

**Comment by jgm** [comment]
I'm sorry, it made no difference.

**Comment by jgm** [comment]
Looks like deleting my node_modules and doing npm install worked.

**Comment by jgm** [comment]
published!

**Comment by danielbachhuber** [comment]
FYI - v0.29.2 seems to have broken use of `import commonmark from 'commonmark';`.

**Comment by jgm** [comment]
@danielbachhuber I'm open to suggestions -- I'm a bit lost on modern JavaScript packaging conventions.  (I'm really a Haskell programmer!)

**Comment by danielbachhuber** [comment]
@jgm I don't know either, to be honest. I've only ever used JS libraries; never maintained one. Just wanted to make sure others were aware, at the least.
